export const MOCK_CURRENT_USER = {
  firstName: 'Mohamed',
}

export const MOCK_RECIPES = [
  {
    id: 1,
    title: 'Blueberry Pancakes',
    cuisine: 'American',
    time: '20 min',
    difficulty: 'Easy',
    tags: ['breakfast'],
    isFavorite: true,
    imageUrl: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1400&q=80',
    description: 'Fluffy pancakes loaded with fresh blueberries and a hint of vanilla.',
    servings: 4,
    ingredients: ['2 cups flour', '2 eggs', '1.5 cups milk', '1 cup blueberries', '2 tbsp sugar', '1 tsp baking powder'],
    steps: ['Whisk dry ingredients in a bowl.', 'Mix eggs and milk, then combine with dry ingredients.', 'Fold in blueberries gently.', 'Cook on a hot griddle until golden on both sides.'],
  },
  {
    id: 2,
    title: 'Avocado Toast',
    cuisine: 'Modern',
    time: '10 min',
    difficulty: 'Easy',
    tags: ['breakfast'],
    isFavorite: true,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1400&q=80',
    description: 'Crispy toast topped with creamy avocado, lemon, and chili flakes.',
    servings: 2,
    ingredients: ['2 slices sourdough', '1 ripe avocado', '1 tsp lemon juice', 'Salt', 'Chili flakes'],
    steps: ['Toast bread slices.', 'Mash avocado with lemon juice and salt.', 'Spread avocado on toast.', 'Top with chili flakes and serve.'],
  },
  {
    id: 3,
    title: 'Spicy Chicken Tacos',
    cuisine: 'Mexican',
    time: '30 min',
    difficulty: 'Easy',
    tags: ['lunch'],
    isFavorite: true,
    imageUrl: 'https://images.unsplash.com/photo-1613514785940-daed07799d9b?auto=format&fit=crop&w=1400&q=80',
    description: 'Juicy spiced chicken wrapped in warm tortillas with fresh toppings.',
    servings: 4,
    ingredients: ['500g chicken thighs', '8 tortillas', '1 tsp paprika', '1 tsp cumin', '1 cup shredded lettuce', 'Salsa'],
    steps: ['Season chicken with spices.', 'Cook chicken until done and slice.', 'Warm tortillas.', 'Assemble tacos with chicken, lettuce, and salsa.'],
  },
  {
    id: 4,
    title: 'Greek Chicken Bowl',
    cuisine: 'Mediterranean',
    time: '25 min',
    difficulty: 'Easy',
    tags: ['lunch'],
    isFavorite: true,
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1400&q=80',
    description: 'A balanced rice bowl with chicken, cucumber, tomato, olives, and feta.',
    servings: 3,
    ingredients: ['2 chicken breasts', '2 cups cooked rice', '1 cucumber', '1 tomato', '1/3 cup olives', '1/2 cup feta'],
    steps: ['Cook and slice chicken.', 'Prep vegetables.', 'Layer rice in bowls.', 'Top with chicken, vegetables, olives, and feta.'],
  },
  {
    id: 5,
    title: 'Mushroom Risotto',
    cuisine: 'Italian',
    time: '40 min',
    difficulty: 'Medium',
    tags: ['dinner'],
    isFavorite: true,
    imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=1400&q=80',
    description: 'Creamy arborio rice with sautéed mushrooms and parmesan.',
    servings: 4,
    ingredients: ['1.5 cups arborio rice', '300g mushrooms', '1 onion', '4 cups stock', '1/2 cup parmesan', '2 tbsp butter'],
    steps: ['Sauté onion and mushrooms.', 'Toast rice briefly.', 'Add stock gradually while stirring.', 'Finish with butter and parmesan.'],
  },
  {
    id: 6,
    title: 'Lemon Herb Salmon',
    cuisine: 'Mediterranean',
    time: '20 min',
    difficulty: 'Medium',
    tags: ['dinner'],
    isFavorite: true,
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1400&q=80',
    description: 'Pan-seared salmon with lemon, garlic, and fresh herbs.',
    servings: 2,
    ingredients: ['2 salmon fillets', '1 lemon', '2 garlic cloves', '1 tbsp olive oil', 'Parsley', 'Salt and pepper'],
    steps: ['Season salmon fillets.', 'Sear in olive oil skin-side down.', 'Add garlic and lemon juice.', 'Finish with chopped parsley.'],
  },
  {
    id: 7,
    title: 'Shakshuka',
    cuisine: 'Middle Eastern',
    time: '28 min',
    difficulty: 'Easy',
    tags: ['breakfast', 'dinner'],
    isFavorite: true,
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=1400&q=80',
    description: 'Poached eggs in a warmly spiced tomato and pepper sauce.',
    servings: 3,
    ingredients: ['4 eggs', '1 can crushed tomatoes', '1 red pepper', '1 onion', '1 tsp cumin', '1 tsp paprika'],
    steps: ['Sauté onion and pepper.', 'Add tomatoes and spices, simmer.', 'Make wells and crack eggs in.', 'Cover and cook until eggs set.'],
  },
  {
    id: 8,
    title: 'Teriyaki Rice Bowl',
    cuisine: 'Japanese',
    time: '22 min',
    difficulty: 'Easy',
    tags: ['lunch', 'dinner'],
    isFavorite: false,
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1400&q=80',
    description: 'Sweet-savory teriyaki chicken served over steamed rice.',
    servings: 4,
    ingredients: ['500g chicken', '3 cups cooked rice', '1/3 cup soy sauce', '2 tbsp honey', '1 tbsp ginger', '1 tbsp sesame seeds'],
    steps: ['Cook chicken pieces in a pan.', 'Stir in teriyaki sauce ingredients.', 'Simmer until glossy.', 'Serve over rice with sesame seeds.'],
  },
]
